# Generated by Django 4.0 on 2021-12-11 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='videos/')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
